### ISSUE TITLE
Multi-Level Subdomains

### ISSUE THREAD

**Issue by SarfarazAliKhan** [kalmhq/kalm#129]
Hey,

Recently I have been looking for a dashboard which can manage routes for k8s but then later I found Kalm scrolling through Reddit.
Thanks for your great work!

So the issue is when I'm try to add multi-level subdomains like foo.bar.example.com in routes it gives this error
![Screen Shot 2020-09-04 at 2 40 04 PM](https://user-images.githubusercontent.com/32435359/92235563-8de3cb80-eebc-11ea-82c9-22faa2e3c345.png)

**Comment by infrar** [comment]
I tried playing around with this a bit and I think multi-level subdomains are working. I wonder if the issue could be due to not trimming leading/trailing spaces. For example when I enter the following three domains:

![Screenshot from 2020-09-04 08-38-27](https://user-images.githubusercontent.com/67806321/92257572-4f351d80-ee8a-11ea-9bb0-97810ecbf31d.png)

"secondlevel.blog.kapp.live" - works and is showing green because IP is configured to point to the cluster
"foo.bar.example.com" - works but shows orange warning because IP is not pointing to the cluster
"foo.bar.example.com " - fails because of a **trailing space**

There should be a fix to trim this input field.

(This is just a guess from looking at the screenshot, would be great if @SarfarazAliKhan could confirm or reject)

**Comment by SarfarazAliKhan** [comment]
No there are no trailing spaces but I’m still getting the same error. I tested again and found that multi-level subdomains are working only if main domain is equal to or less than 4 letters. Also .email TLD is not working at all which I used just for testing.
![Screen Shot 2020-09-06 at 12 48 41 PM](https://user-images.githubusercontent.com/32435359/92323189-57828980-f03f-11ea-9aec-e4e7ead8b9dd.png)

**Comment by iAladdin** [comment]
@SarfarazAliKhan 
Thank you for your report.
Currently, leading or trailing spaces are incorrectly counted as part of the user's input.
We will fix this, formalized, and trimmed user input before checking the domain format.

**Comment by iAladdin** [comment]
@SarfarazAliKhan
Hi, we have refactored certificate related components, this issue has fixed.
We'll release this version later.

**Comment by iAladdin** [comment]
We have changed verify logic and UX,  close this for now.
Please try the new version.
Thanks!
